my_game.py
Wrap on Y axis not tested :rice: :))
=> Player wraps on x and y

my_game.py
background color chanced to black
=> Change background color

my_game.py
Added class Asteroids. Added single Asteroids. Asteroids spawn in center of screen.
=> Asteroids added.

my_game.py
Draw lives on the screen under.
=> Draw lives 

my_game.py
Asteroids wraps around the screen.
=> Asteroids wraps

my_game.py
Player rotates with variable :)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))
=> Player rotates

my_game.py
…d by player, asteroids and possible new sprites.
=> Screen wrap

my_game.py
Player has functioning rocket engine 
> - 0 -
=> player_thrusts

my_game.py
Mangler skift tilfældig retning en gang imellem.
=> Added UFO that wraps.

my_game.py
When shots are fired, they travel in the right direction
=> Shots fired by player fly in the same direction as the players direction when the shot was fired

my_game.py
Wonderfulled fixed code by a wonderfully fixed (?) person
=> Player thrust right place math

my_game.py
=> Max fastness

my_game.py
- Player looses a life when hit by asteroid
- The asteroid is then deleted
=> player looses a life when hit by asteroid. The asteroid is then deleted

my_game.py
More asteroids spawn after time defined by variable **ASTEROIDS_TIMER**
=> Several asteroids spawn

my_game.py
Game should be reset when player looses all of their lives. I'm not entirely sure, as it is currently impossible to die in the game :)
=> Game resets when player dies

my_game.py
Asteroids_timer does not exist, so I renamed it to asteroids-timer_seconds which is the name of the variable I was trying to use :))
=> fixed wrong variable name

my_game.py
when you lose a life a sound plays
=> Add sound when your hit asteriod

my_game.py
- Asteroids move other ways than verically
- Asteroids split and shrink in size when hit by player_shot
*The changes in size are very big (even though the asteroids get smaller (haha))*
=> Asteroids split

my_game.py
Almost identical methods setup and reset has been replaced by one method "reset".
=> Merge setup and reset

my_game.py
Text taken from global dictionary is displayed on the game over screen (in three words because this is English...)
Don't know if it's how you pictured it to be (especially with the dictionary), but it exists and it works :+1: :heart_eyes:
=> Text with user and scores from list-dictionary in the top of the program

my_game.py
You can now see your score above the leaderboard with position on the leaderboard. And if you score is in top 10 it is highlighted on the leaderboard.
=> Improved game over screen
